openapi: 3.0.0
info:
  version: 1.0.0
  title: Lumin Sign Api Reference
  description: |
    The Lumin Sign API Reference supplies a wide range of eSignature tools for your application.

    Some useful links:
    - [The document repository](https://github.com/luminpdf/luminsign-docs)
    - [The source API definition for the Lumin Sign API](https://github.com/luminpdf/luminsign-docs/blob/main/openapi.yaml)
    - [Authentication for using API](/luminsign-docs/docs/api/authentication/)
  contact:
    name: API Support
    email: support@example.com
    url: http://example.com/support
  externalDocs:
    description: Find out more
    url: http://example.com
servers:
  - url: https://api-staging.luminpdf.com/v1
    description: Staging server
tags:
  - name: Signature Request
    description: Everything about Signature Request
  - name: User
    description: Everything about User
paths:
  /signature_request/{signature_request_id}:
    get:
      summary: Get Signature Request
      description: Get Signature Request by id.
      security:
        - ApiKey: []
      tags:
        - Signature Request
      parameters:
        - in: path
          name: signature_request_id
          schema:
            type: string
          required: true
          description: ID of the Signature Request to get
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                required:
                  - signature_request
                properties:
                  signature_request:
                    description: Contains information about a Signature Request.
                    $ref: '#/components/schemas/SignatureRequest'
        '4xx':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /signature_request/send:
    post:
      summary: Send Signature Request
      description: Creates and sends a new Signature Request with the submitted documents.
      security:
        - ApiKey: []
      tags:
        - Signature Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureRequestDTO'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                required:
                  - signature_request
                properties:
                  signature_request:
                    description: Contains information about a Signature Request.
                    $ref: '#/components/schemas/SignatureRequest'
        '4xx':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user/info:
    get:
      summary: Get User Information
      description: Get information of current user by API Key
      security:
        - ApiKey: []
      tags:
        - User
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                type: object
                required:
                  - user
                properties:
                  user:
                    description: Contains information about a User.
                    $ref: '#/components/schemas/User'
        '4xx':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    ApiKey:
      type: apiKey
      name: X-API-KEY
      in: header
  schemas:
    Signer:
      type: object
      required:
        - email_address
        - name
      properties:
        email_address:
          type: string
        name:
          type: string
    Viewer:
      type: object
      required:
        - email_address
        - name
      properties:
        email_address:
          type: string
        name:
          type: string
    SignatureRequest:
      type: object
      required:
        - signature_request_id
        - title
        - created_at
        - expires_at
        - details_url
        - status
        - signers
      properties:
        signature_request_id:
          type: string
          description: The unique identifier for the Signature Request.
        title:
          type: string
          description: The title of the Signature Request.
        created_at:
          type: string
          description: The time the Signature Request was created.
        expires_at:
          type: string
          description: The time the Signature Request will expire.
        details_url:
          type: string
          description: The url to view the Signature Request in the browser.
        status:
          type: string
          description: The status of the Signature Request.
          enum:
            - NEED_TO_SIGN
            - WAITING_FOR_OTHERS
            - APPROVED
            - REJECTED
        signers:
          type: array
          items:
            required:
              - email_address
              - name
              - is_approved
              - status
            allOf:
              - $ref: '#/components/schemas/Signer'
              - properties:
                  is_approved:
                    type: boolean
                    description: Whether the Signer has approved the Signature Request.
                  status:
                    type: string
                    description: The status of the Signer.
                    enum:
                      - NEED_TO_SIGN
                      - APPROVED
                      - REJECTED
          description: The Signers of the Signature Request.
    User:
      type: object
      required:
        - email
        - id
        - name
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
    SignatureRequestDTO:
      type: object
      required:
        - signers
        - title
        - expires_at
      properties:
        file_url:
          type: string
          description: The url of the file, which will be downloaded and signed. This endpoint requires either file or file_url, but not both.
        file:
          type: string
          format: binary
          description: The uploaded file to send for signature. This endpoint requires either file or file_url, but not both.
        signers:
          type: array
          items:
            $ref: '#/components/schemas/Signer'
          description: Add Signers to your Signature Request.
        viewers:
          type: array
          items:
            $ref: '#/components/schemas/Viewer'
          description: Add Viewers to your Signature Request.
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: The title you want to give the Signature Request.
        expires_at:
          type: int64
          format: unix-epoch
          description: When the Signature Request will expire. This is a unix epoch timestamp (miliseconds). Should be later than today.
        use_text_tags:
          type: boolean
          description: Set to `true` to enable Text Tag parsing in your document. Your Text Tags will be converted into UI components for the user to interact with. Defaults to `false`.
      example:
        file_url: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf
        signers:
          - email_address: nhuttm@luminpdf.com
            name: Nhut Tran
          - email_address: nhuttm1@luminpdf.com
            name: Hieu Do
          - email_address: nhuttm5@luminpdf.com
            name: Hien Tran
        viewers:
          - email_address: nhuttm3@luminpdf.com
            name: Cong Nguyen
          - email_address: nhuttm2@luminpdf.com
            name: Tien Tran
          - email_address: nhuttm4@luminpdf.com
            name: Tan Nguyen
        title: My first request signing document
        expires_at: 1727510980694
        use_text_tags: false
    Error:
      type: object
      required:
        - error_code
        - error_message
      properties:
        error_code:
          type: string
        error_message:
          type: string
