/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [{type: 'autogenerated', dirName: '.'}],
  // Sidebar for the beta-docs instance
  // betaSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Authentication',
  //     items: [
  //       'beta/authorization/overview',
  //       'beta/authorization/api-key-authentication',
  //       {
  //         type: 'category',
  //         label: 'OAuth 2.0 Authentication',
  //         items: [
  //           'beta/authorization/oauth2-authentication/creating-oauth2-application',
  //           'beta/authorization/oauth2-authentication/private-authorization-code',
  //           'beta/authorization/oauth2-authentication/public-authorization-code',
  //           'beta/authorization/oauth2-authentication/scopes',
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: 'Webhooks',
  //     items: [
  //       'beta/api/webhooks/app-callbacks',
  //     ],
  //   },
  // ],
};

module.exports = sidebars;
