openapi: 3.0.0
servers:
  - url: https://auth.luminpdf.com
    description: OAuth2 server
info:
  description: |
    LuminPDF OAuth2 specification
  title: OAuth2 specification
  version: 1.0.0
tags:
  - name: Implicit flow
    description: OAuth2 with implicit flow
  - name: Authorization code
    description: OAuth2 with authorization code flow
components:
  schemas:
    Implicit:
      $ref: 'components/implicit.yml#/components/schemas/Implicit'
      xml:
        name: Implicit
    PrivateAuthorizationCode:
      $ref: 'components/authorization_code.yml#/components/schemas/PrivateAuthorizationCode'
      xml:
        name: PrivateAuthorizationCode
    PublicAuthorizationCode:
      $ref: 'components/authorization_code.yml#/components/schemas/PublicAuthorizationCode'
      xml:
        name: PublicAuthorizationCode