openapi: 3.0.0
servers:
  - url: https://kratos-auth-test.luminpdf.com
    description: OAuth2 server
info:
  description: |
    LuminPDF OAuth2 specification
  title: OAuth2 specification
  version: 1.0.0
tags:
  - name: Implicit flow
    description: OAuth2 with implicit flow
  - name: Authorization code
    description: OAuth2 with authorization code flow
components:
  schemas:
    Implicit:
      type: object
      required:
        - response_type
        - client_id
        - redirect_uri
        - scope
      properties:
        response_type:
          type: string
          description: Which grant to execute.
          enum:
            - token
            - token id_token
        client_id:
          type: string
          description: Your app Client ID
        redirect_uri:
          type: string
          format: uri
          description: >-
            The redirect_uri where authentication responses will be sent and
            received. It is one of the redirect URIs you registered in the Lumin
            Sign.
        scope:
          type: string
          description: >
            A space-delimited list of scopes that identify the resources that
            your application want to access. Supported scopes are:


            openid, bananasign:document.create
        state:
          type: string
          description: Specifies any string value for prevent attacks and redirect users
        nonce:
          type: string
          description: >-
            This value is required if use request for id_token scope. Value for
            prevent playback attack, you must compare with nonce in id_token if
            set
      xml:
        name: Implicit
    AuthorizationCode:
      type: object
      required:
        - response_type
        - client_id
        - redirect_uri
        - scope
      properties:
        response_type:
          type: string
          description: Which grant to execute.
          enum:
            - code
            - code id_token
        client_id:
          type: string
          description: Your app Client ID
        redirect_uri:
          type: string
          format: uri
          description: >-
            The redirect_uri where authentication responses will be sent and
            received. It is one of the redirect URIs you registered in the Lumin
            Sign.
        scope:
          type: string
          description: >
            A space-delimited list of scopes that identify the resources that
            your application want to access. Supported scopes are:


            openid, bananasign:document.create
        state:
          type: string
          description: Specifies any string value for prevent attacks and redirect users
        nonce:
          type: string
          description: >-
            This value is required if use request for id_token scope. Value for
            prevent playback attack, you must compare with nonce in id_token if
            set
      xml:
        name: AuthorizationCode
